---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - This configuration file uses some advanced YAML features (namely anchors) which may not be correctly displayed
#   by syntax highlighting
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/bsk/bas-style-kit/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - AWS IAM id/secret keys for 'bas-gitlab-deploy-bas-style-kit' user
# > AWS_ACCESS_KEY_ID: "[Sensitive]"
# > AWS_SECRET_ACCESS_KEY: "[Sensitive]"
#
# - Snyk
# > SNYK_TOKEN: "[Sensitive]"

# == Job Templates ==

.job_template_s3_sync: &job_template_s3_sync
  image:
    name: governmentpaas/awscli:latest
    entrypoint: [""]
  before_script:
    - "export CI_BUILD_TAG_SHORT=`echo $CI_COMMIT_TAG | cut -c 2-`"

# == Global settings ==

stages:
  # - security
  - build
  - lint
  - process
  - package
  - review
  - deploy

image:
  name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/app:latest-alpine
  entrypoint: [""]

variables:
  CDN_BUCKET: cdn.web.bas.ac.uk
  TESTBED_BUCKET: style-kit-testbed.web.bas.ac.uk
  APP_NAME: bas-style-kit
  REVIEW_APP_DOMAIN: bas-style-kit-testbed.s3-website-eu-west-1.amazonaws.com
  SNYK_ORG: antarctica
  SNYK_PROJECT_NAME_APP: bas-style-kit-core
  SNYK_PROJECT_NAME_TESTBED: bas-style-kit-testbed

# == Jobs ==

# node-dependencies-app:
#   stage: setup
#   script:
#     - "yarn install --frozen-lockfile"
#   artifacts:
#     name: "$CI_BUILD_TOKEN-node-dependencies-app"
#     paths:
#       - node_modules
#     expire_in: 1 hour

# node-dependencies-testbed:
#   stage: setup
#   image:
#     name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
#     entrypoint: [""]
#   script:
#     - "cd testbed"
#     - "yarn install --frozen-lockfile"
#   artifacts:
#     name: "$CI_BUILD_TOKEN-node-dependencies-testbed"
#     paths:
#       - testbed/node_modules
#     expire_in: 1 hour


# Disabled until https://github.com/snyk/nodejs-lockfile-parser/issues/56 is resolved
#
# check-dependencies-app:
#   stage: security
#   image:
#     name: snyk/snyk-cli:npm
#     entrypoint: [""]
#   script:
#     - "snyk test --file=yarn.lock"
#     - "snyk monitor --file=yarn.lock --project-name=$SNYK_PROJECT_NAME_APP --org=$SNYK_ORG"

# Disabled until https://github.com/snyk/nodejs-lockfile-parser/issues/56 is resolved
#
# check-dependencies-testbed:
#   stage: security
#   image:
#     name: snyk/snyk-cli:npm
#     entrypoint: [""]
#   script:
#     - "snyk test --file=testbed/yarn.lock"
#     - "snyk monitor --file=testbed/yarn.lock --project-name=$SNYK_PROJECT_NAME_TESTBED --org=$SNYK_ORG"

compile-sass-app:
  stage: build
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp build--css"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-styles-app"
    paths:
      - dist/css/styles-bsk.css
      - dist/css/bootstrap-bsk.css
      - dist/css/fonts-bsk.css
      - dist/css/bas-style-kit.css
      - dist/css/bas-style-kit.min.css
    expire_in: 1 week

compile-sass-testbed:
  stage: build
  image:
    name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    entrypoint: [""]
  before_script:
    - "cd testbed"
    - "export TESTBED_VERSION=$CI_COMMIT_REF_SLUG"
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp build--css"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-styles-testbed"
    paths:
      - testbed/public/assets/css/
    expire_in: 1 week

compile-js-app:
  stage: build
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
      - "yarn gulp build--js"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-scripts-app"
    paths:
      - dist/js/bas-style-kit.js
      - dist/js/bas-style-kit.min.js
    expire_in: 1 week

compile-js-testbed:
  stage: build
  image:
    name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    entrypoint: [""]
  before_script:
    - "cd testbed"
    - "export TESTBED_VERSION=$CI_COMMIT_REF_SLUG"
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp build--js"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-styles-testbed"
    paths:
      - testbed/public/assets/js/
    expire_in: 1 week

compile-pug-testbed:
  stage: build
  image:
    name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    entrypoint: [""]
  before_script:
    - "cd testbed"
    - "export TESTBED_VERSION=$CI_COMMIT_REF_SLUG"
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp build--pages"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-templates-app"
    paths:
      - testbed/public/s
      - testbed/public/p
      - testbed/public/legal
      - testbed/public/index.html
      - testbed/public/error.html
    expire_in: 1 week

copy-fonts-app:
  stage: build
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp copy--fonts"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-fonts-app"
    paths:
      - dist/fonts
    expire_in: 1 week

copy-images-app:
  stage: build
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp copy--img"
    - "yarn gulp generate--favicon--manifests"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-imgs-app"
    paths:
      - dist/img
    expire_in: 1 week

copy-images-testbed:
  stage: build
  image:
    name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    entrypoint: [""]
  before_script:
    - "cd testbed"
    - "export TESTBED_VERSION=$CI_COMMIT_REF_SLUG"
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp copy--img"
  only:
    - merge_requests
    - master
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-imgs-testbed"
    paths:
      - testbed/public/assets/img
    expire_in: 1 week

lint-sass-app:
  stage: lint
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp lint--sass"
  needs: ["compile-sass-app"]
  only:
    - merge_requests
    - master

lint-js-app:
  stage: lint
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp lint--js"
  needs: ["compile-js-app"]
  only:
    - merge_requests
    - master

compute-sri-app:
  stage: process
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp sri"
  artifacts:
    name: "$CI_BUILD_TOKEN-dist-sri"
    paths:
      - dist/bas-style-kit.sri.json
    expire_in: 1 week
  needs: [
    "compile-sass-app",
    "compile-js-app"
  ]
  only:
    - merge_requests
    - master

review:
  <<: *job_template_s3_sync
  stage: review
  script:
    - aws s3 sync --delete testbed/public/ s3://$TESTBED_BUCKET/$CI_COMMIT_REF_SLUG/
    - aws s3 sync --delete dist/ s3://$TESTBED_BUCKET/$CI_COMMIT_REF_SLUG/dist/
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://style-kit-testbed.web.bas.ac.uk/$CI_COMMIT_REF_SLUG/
    on_stop: stop_review

stop_review:
  <<: *job_template_s3_sync
  stage: review
  script:
    - aws s3 rm --recursive s3://$TESTBED_BUCKET/$CI_COMMIT_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  dependencies: []

package-app:
  stage: package
  before_script:
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp archive--dist"
  artifacts:
    name: "$CI_BUILD_TOKEN-zip-app"
    paths:
      - "bas-style-kit.zip"
    expire_in: 1 week
  only:
    - master
    - tags

package-testbed:
  stage: package
  image:
    name: docker-registry.data.bas.ac.uk/web-apps/bsk/bas-style-kit/testbed:latest-alpine
    entrypoint: [""]
  before_script:
    - "cd testbed"
    - "yarn set version berry"
    - "yarn install"
  script:
    - "yarn gulp archive--public"
  artifacts:
    name: "$CI_BUILD_TOKEN-zip-testbed"
    paths:
      - "testbed/bas-style-kit-testbed.zip"
    expire_in: 1 week
  only:
    - master
    - tags

upload-app:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - tags
  script:
    - "aws s3 sync --delete dist/ s3://$CDN_BUCKET/$APP_NAME/$CI_BUILD_TAG_SHORT/"

upload-testbed:
  <<: *job_template_s3_sync
  stage: deploy
  only:
    - master
  script:
    - aws s3 sync --delete testbed/public/ s3://$TESTBED_BUCKET/$CI_COMMIT_REF_SLUG/
    - aws s3 sync --delete dist/ s3://$TESTBED_BUCKET/$CI_COMMIT_REF_SLUG/dist/
  environment:
    name: testbed
    url: https://style-kit-testbed.web.bas.ac.uk/$CI_COMMIT_REF_SLUG/testbed/
